-- ============================================================================
-- 01 — Environment Setup & RBAC
-- Warehouses, medallion database/schemas, least-privilege role hierarchy, grants
-- Run as ACCOUNTADMIN. Replace <YOUR_USER> with your Snowflake username.
-- ============================================================================
USE ROLE ACCOUNTADMIN;

-- ---------------------------------------------------------------------------
-- Compute: two warehouses for workload isolation + FinOps (auto-suspend 60s)
-- ---------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS FRAUD_INGEST_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Transformation (Dynamic Tables) + ML scoring';

CREATE WAREHOUSE IF NOT EXISTS FRAUD_APP_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Streamlit Audit Command Center';

-- ---------------------------------------------------------------------------
-- Medallion database + schemas (clear trust boundaries = auditable lineage)
-- ---------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS FRAUD_DB COMMENT = 'Real-Time Fraud & Audit Pipeline';
CREATE SCHEMA IF NOT EXISTS FRAUD_DB.RAW        COMMENT = 'Landing zone - raw streamed transactions';
CREATE SCHEMA IF NOT EXISTS FRAUD_DB.HARMONIZED COMMENT = 'Cleaned & enriched - Dynamic Tables';
CREATE SCHEMA IF NOT EXISTS FRAUD_DB.ANALYTICS  COMMENT = 'Curated serving layer - ML scores & app views';

-- ---------------------------------------------------------------------------
-- Role model: separate ACCESS roles (object privileges) from the
-- FUNCTIONAL role (job function). Functional role is granted to users.
-- ---------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS FRAUD_DB_READ      COMMENT = 'Read access across FRAUD_DB';
CREATE ROLE IF NOT EXISTS FRAUD_DB_READWRITE COMMENT = 'Read/write access across FRAUD_DB';
CREATE ROLE IF NOT EXISTS FRAUD_ENGINEER     COMMENT = 'Functional role: builds & operates the fraud pipeline';

-- READ role
GRANT USAGE ON DATABASE FRAUD_DB TO ROLE FRAUD_DB_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READ;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READ;
GRANT SELECT ON ALL TABLES    IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READ;
GRANT SELECT ON ALL VIEWS     IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READ;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READ;

-- READWRITE role (inherits READ, adds create + DML)
GRANT ROLE FRAUD_DB_READ TO ROLE FRAUD_DB_READWRITE;
GRANT USAGE ON DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE TABLE         ON ALL SCHEMAS    IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE TABLE         ON FUTURE SCHEMAS IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE VIEW          ON ALL SCHEMAS    IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE VIEW          ON FUTURE SCHEMAS IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE DYNAMIC TABLE ON ALL SCHEMAS    IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE DYNAMIC TABLE ON FUTURE SCHEMAS IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE STREAMLIT ON SCHEMA FRAUD_DB.ANALYTICS TO ROLE FRAUD_DB_READWRITE;
GRANT CREATE STAGE     ON SCHEMA FRAUD_DB.ANALYTICS TO ROLE FRAUD_DB_READWRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES    IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE FRAUD_DB TO ROLE FRAUD_DB_READWRITE;
GRANT USAGE, OPERATE ON WAREHOUSE FRAUD_INGEST_WH TO ROLE FRAUD_DB_READWRITE;
GRANT USAGE, OPERATE ON WAREHOUSE FRAUD_APP_WH    TO ROLE FRAUD_DB_READWRITE;

-- Feature-specific privileges added across phases:
GRANT CREATE PIPE       ON SCHEMA FRAUD_DB.RAW       TO ROLE FRAUD_DB_READWRITE;  -- Phase 3: SDK auto-creates default pipe
GRANT CREATE MODEL      ON SCHEMA FRAUD_DB.ANALYTICS TO ROLE FRAUD_DB_READWRITE;  -- Phase 5: Model Registry
GRANT CREATE EXPERIMENT ON SCHEMA FRAUD_DB.ANALYTICS TO ROLE FRAUD_DB_READWRITE;  -- Phase 5: Experiment Tracking
GRANT CREATE ALERT      ON SCHEMA FRAUD_DB.ANALYTICS TO ROLE FRAUD_DB_READWRITE;  -- Phase 7: Alerts
GRANT USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU  TO ROLE FRAUD_ENGINEER;      -- Phase 6: SiS container runtime
GRANT EXECUTE ALERT         ON ACCOUNT TO ROLE FRAUD_ENGINEER;                    -- Phase 7
GRANT EXECUTE MANAGED ALERT ON ACCOUNT TO ROLE FRAUD_ENGINEER;                    -- Phase 7: serverless alerts

-- Wire functional role into the system hierarchy + grant to the user
GRANT ROLE FRAUD_DB_READWRITE TO ROLE FRAUD_ENGINEER;
GRANT ROLE FRAUD_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE FRAUD_ENGINEER TO USER <YOUR_USER>;
